kind: ConfigMap
metadata:
  name: traefik.yml
apiVersion: v1
data:
  traefik.yml: |
    api: 
      insecure: true  # 配置traefik的dashboard面板不走https也可以访问
      
    entryPoints:
      web:  # entrypoint的名字，可以自定义
        address: ":80"
      abcd: # entrypoint的名字，可以自定义
        address: ":3306"

    # 开启traefik的日志，方便查问题
    accesslog:
      addInternals: true
    
    # 规则以及相关资源的提供者
    providers:
      kubernetesingress: true  # k8s自带的ingress资源
      kubernetescrd: true      # k8s的crd资源，比如traefik自定义的ingressRoute等
