apiVersion: v1
data:
  server.properties: |
    process.roles=broker,controller
    node.id=1
    controller.quorum.voters=1@localhost:9093

    # 请注意看这里
    listeners=INNER://:9092,OUTER://:30092,CONTROLLER://:9093
    inter.broker.listener.name=INNER
    advertised.listeners=INNER://$INNER,OUTER://$OUTER
    listener.security.protocol.map=INNER:PLAINTEXT,OUTER:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
    # 请注意看上面

    controller.listener.names=CONTROLLER
    num.network.threads=4
    num.io.threads=8
    socket.send.buffer.bytes=409600
    socket.receive.buffer.bytes=409600
    socket.request.max.bytes=104857600
    replica.fetch.max.bytes=15728640
    log.dirs=/var/log/kafka/data
    num.partitions=2
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    log.retention.minutes=30
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    auto.create.topics.enable=true
    delete.topic.enable=true
    group.initial.rebalance.delay.ms=30000
    message.max.bytes=10485760
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: server.properties
