kind: ConfigMap
metadata:
  name: traefik.yml
apiVersion: v1
data:
  traefik.yml: |
    api:
      insecure: true

    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"
        # 请看这里，如果你是使用的Ingress的话，下面这两行必须要有
        https:
          tls: {}
      mysql: # 看这里，新增一个名字叫mysql的entrypoint
        address: ":3306"
      kafka:
        address: ":9092"

    # 开启traefik的日志，方便查问题
    accesslog:
      addInternals: true

    # 规则以及相关资源的提供者
    providers:
      kubernetesingress: true  # k8s自带的ingress资源
      kubernetescrd: true      # k8s的crd资源，比如traefik自定义的ingressRoute等

    tls:
      stores:
        default:
          defaultCertificate:
            certFile: /certs/tls.crt
            keyFile: /certs/tls.key
